config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  root "ideas#index"
  
  resources :users, only: [:new, :create]

  resources :sessions, only: [:create]
  get 'session/new', to: 'sessions#new'
  delete '/sign_out', to: 'sessions#destroy'

  resources :ideas do
    resources :reviews, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/idea.rb
class Idea < ApplicationRecord
    belongs_to :user
    has_many :reviews, dependent: :destroy
    has_many :users, through: :reviews
    has_many :likes, dependent: :destroy
    has_many :users, through: :likes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :idea

  validates :idea_id, uniqueness: {scope: :user_id}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :idea
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :ideas, dependent: :destroy
    has_many :reviews, dependent: :destroy

    has_many :likes, dependent: :destroy
    has_many :liked_ideas, through: :likes, source: :idea

    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, length: {minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def authenticate_user!
        if !user_signed_in?
            flash[:alert] = "Please sign in first!"
            redirect_to session_new_path
        end
    end
    helper_method :authenticate_user!

    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?
    
    def current_user
        @current_user ||= User.find_by_id cookies[:user_id]
    end
    helper_method :current_user
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy, :edit, :update]
  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new params.require(:idea).permit(:title, :body)

    if @idea.save
      redirect_to root_path
    else
      p "didnt save"
    end
  end

  def show
    @idea = Idea.find params[:id]
    @username = User.find_by_id @idea.user_id
    @review = Review.new
    @reviews = Review.where idea_id: @idea.id
    if user_signed_in?
      @likes = Like.where(idea_id: @idea.id, user_id: current_user.id).first
    end
  end

  def index
    @idea = Idea.all.order(id: :desc)
    p @idea[0]
    render status: 202
  end

  def destroy
    @idea = Idea.find params[:id]
    author = User.find_by_id @idea.user_id
    if current_user == author
      @idea.destroy
      redirect_to root_path
    end
  end

  def edit
    @idea = Idea.find params[:id]
  end

  def update
    @idea = Idea.find params[:id]
    author = User.find_by_id @idea.user_id

    if current_user == author
      if @idea.update params.require(:idea).permit(:title, :body)
          redirect_to idea_path(@idea.id)
      else 
          redirect_to edit_idea_path
      end
    else
      flash[:alert] = "not authroized to make changes" 
      redirect_to edit_idea_path
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!

    def create
        like = Like.new
        idea = Idea.find params[:idea_id]
        like.idea = idea
        like.user = current_user
        if like.save
            flash[:notice] = "thank you for the like"
            redirect_to idea_path(idea.id)
        else 
            p "did not save like or already liked"
            redirect_to idea_path(idea.id)
        end

    end

    def destroy
        idea = Idea.find params[:idea_id]
        like = current_user.likes.find params[:id]
        if like.destroy
            flash[:notice] = "Unliked"
            redirect_to idea_path(idea.id)
        else
            p "could not unlike"
        end
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_idea

    def create
        @idea = Idea.find params[:idea_id]
        @review = Review.new params.require(:review).permit(:title, :body)
        @review.user_id = cookies[:user_id]
        @review.idea_id = @idea.id
        if @review.save
            puts "saved"
            redirect_to idea_path(@idea.id)
        else
            puts 'did not save'
            redirect_to idea_path(@idea.id)
        end
    end

    def destroy
        p cookies[:user_id]
        @review = Review.find params[:id]
        p @review.user_id
        if @review.user_id == cookies[:user_id].to_i 
            @review.destroy
            p "destroyed"
            redirect_to idea_path(@idea.id)
        else
            p "could not destory"
        end
    end

    private

    def find_idea
        @idea = Idea.find params[:idea_id]
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.find_by(email: user_params[:email])
        p user_params
        
        if @user && @user.authenticate(user_params[:password])
            p @user
            flash[:notice] = "Logged In"
            cookies[:user_id] = @user.id
            redirect_to root_path
        else 
            p @user
            flash[:notice] = "Invalid email or password"
            redirect_to session_new_path
        end
    end

    def destroy
        cookies[:user_id] = nil
        flash.notice = "Logged out"
        redirect_to root_path
    end
    
    private

    def user_params
        params.require(:user).permit(:name, :email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.password == @user.password_confirmation
      @user.save
      redirect_to root_path
    else
      flash[:notice] = "Password is not the same"
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/edit.html.erb
<%= form_with model:@idea do |form| %>
    <div>
    <%= form.label :title, "Title"%>
    <br>
    <%= form.text_field :title%>
    <br>
    <%= form.label :body%>
    <br>
    <%= form.text_field :body%>
    <br>
    <%= form.submit "Update"%>
    </div>
<%end%>

app/views/ideas/index.html.erb
<% @idea.each do |idea| %>
    <div class = "container" >
    <h3 class = "title" > <%= link_to idea.title, idea_path(idea.id), class: "title" %> </h3>
    <p class = "preview" > <%= idea.body %> </p>
    <p> likes <%= Like.where(idea_id: idea.id).count %> </p>
    </div>
    <br>
<% end %>

app/views/ideas/new.html.erb
<h1>Ideas#new</h1>
<p>Find me in app/views/ideas/new.html.erb</p>

<%= form_with model:@idea do |form| %>
    <div>
    <%= form.label :title, "Title"%>
    <br>
    <%= form.text_field :title%>
    <br>
    <%= form.label :body%>
    <br>
    <%= form.text_field :body%>
    <br>
    <%= form.submit "Create"%>
    </div>
<%end%>

app/views/ideas/show.html.erb
<div class = "container">
<h2> <%= @idea.title %> </h3>
<p> <%= @idea.body %> </p>
<p> Posted <%= time_ago_in_words(@idea.created_at) %> ago</p>
<p> Created By <%= @username.name %> ago</p>
</div>
<div class = "container"> 
<% if user_signed_in? %>
    <% if @likes.present? %>
        <%= button_to 'Unlike', idea_like_path(@idea.id, @likes.id), method: :delete %>
    <% else %>
        <%= button_to 'Like', idea_likes_path(@idea.id), method: :post %>
    <% end %>
<% else %>
    <p>Please Sign in to Like this Idea</p>
<% end %>
<% if @current_user %>
    <% if @current_user.id == @username.id %>
        <%= button_to("Delete", idea_path, method: :delete)%> 
        <%= link_to 'Edit', edit_idea_path(@idea) %> 
    <% end %>
<% end %>
</div>
<br>

<div class = "container">
    <% if user_signed_in? %>
        <%= form_with(model:[@idea, @review]) do |form| %>
        <h3>
        <%= form.label :title, "Title of Your Review"%>
        </h3>
        <div>
        <%= form.text_field :title, placeholder: "Title"%>
        </div>
        <h3>
        <%= form.label :body, "Review Description"%>
        </h3>
        <div>
        <%= form.text_field :body, placeholder: "Write your review"%>
        </div>
        <%= form.submit "Submit"  %>
        <%end%>
        <% else %>
        <h3>Please Sign In to Create a review</h3>
    <% end %>
    
</div>

<% if @reviews %>
    <% @reviews.each do |review| %>
        <div class = "container">
        <p> <%= review.title %> </p>
        <p> <%= review.body %> </p>
        <p> Created By <%= (User.find_by_id review.user_id).name %></p>
        </div>
    <% if user_signed_in? && current_user.id == review.user_id %>
        <div class = "container">
            <%= button_to("Delete", idea_review_path(@idea.id, review.id), method: :delete) %>
    </div>
    <% end %> 
    <br>
    <% end %>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class = "icon"> 
  <h4 class = "idea-factory"> <a href = "<%= root_path %>" class = "nav-item"> Idea Factory </a></h4>
  </div>
  <hr>
  <div class = "box"><h3 class = "nav-item1"> <%= link_to "New Idea", new_idea_path, class: "nav-item" %> </h3></div>
    <div class = "user-options">
    <%if(user_signed_in?) %>
       <h2>Signed in as <%= current_user.name %> <%= button_to "Log out", sign_out_path, method: :delete, class: "logout" %></h2> 
      
    <% else %>
    <div class = "user-options2" >
      <%= link_to 'Sign In Page', session_new_path, class: "nav-item" %>
      <%= link_to 'Sign Up Page', new_user_path, class: "nav-item"%>
    </div>
    <% end %>
    </div>
    
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= form_with model:@user do |form| %>
    <%= form.label :name, "Name" %>
    <br>
    <%= form.text_field :name %>
    <br>
    <%= form.label :email, "Email" %>
    <br>
    <%= form.text_field :email %>
    <br>
    <%= form.label :password, "Password" %>
    <br>
    <%= form.text_field :password %>
    <br>
    <%= form.label :password_confirmation, "Password Confirmation" %>
    <br>
    <%= form.text_field :password_confirmation %>
    <br>
    <%= form.submit "Sign Up" %>
    <% if flash.notice %>
        <% flash.each do |type, message| %>
        <%= type + " : " + message %>
    <% end %>
  <% end %>
<% end %>